"""``kikai publish`` が書き出すパッケージの形 — 語の模型と、run.sh / env.example /
README.md の字面、そしてディスクへの書き出し。

``kikai_lab.publish`` (op の翻訳) から使われる。こちらは op を知らない。

設計: docs/design/publish_design.md
"""
from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from kikai_lab.operation import OperationError

# パッケージ内で bundle を置く場所と、コンテナ内での見え方。bundle manifest の argv は
# "script_bundles/<id>/root/<file>" という workdir 相対なので、workdir を変えずに済むよう
# bundles/ を project mount の script_bundles/ の位置へ被せる。
PACKAGE_BUNDLE_DIR = "bundles"
CONTAINER_PROJECT_DIR = "/workspace/kikai_project"
CONTAINER_BUNDLE_DIR = f"{CONTAINER_PROJECT_DIR}/script_bundles"


@dataclass(frozen=True)
class Seg:
    """シェル語の一片。``is_var`` なら ``${text}`` として展開される。"""

    text: str
    is_var: bool = False


# 1 つのシェル語 (例: ``"${SRC_DATA}:/workspace/data:ro"`` は 3 片)
Word = tuple[Seg, ...]


@dataclass
class VarSpec:
    """env.example に並ぶ変数 1 つ。``example`` は publish 元で見えていた literal 値。"""

    name: str
    origin: str
    example: str | None = None


@dataclass
class MountRow:
    """README のデータ配置表の 1 行。"""

    variable: str
    target: str
    mode: str
    source_example: str | None


@dataclass
class TranslatedOp:
    index: int
    operation: str
    adapter: str
    command: list[Word] | None = None
    skipped_reason: str | None = None
    bundle_id: str | None = None
    entrypoint: str | None = None


@dataclass
class PublishPlan:
    name: str
    ops: list[TranslatedOp] = field(default_factory=list)
    variables: list[VarSpec] = field(default_factory=list)
    mounts: list[MountRow] = field(default_factory=list)
    bundle_roots: dict[str, Path] = field(default_factory=dict)
    images: list[str] = field(default_factory=list)
    dropped_notes: list[str] = field(default_factory=list)

    @property
    def skipped(self) -> list[TranslatedOp]:
        return [op for op in self.ops if op.command is None]

    @property
    def translated(self) -> list[TranslatedOp]:
        return [op for op in self.ops if op.command is not None]


# ------------------------------------------------------------------ word 組み立て


def word_vars(word: Word) -> list[str]:
    return [seg.text for seg in word if seg.is_var]


def literal(value: str) -> Word:
    return (Seg(value),)


def join_words(*words: Word, separator: str) -> Word:
    """``source:target:mode`` のように、変数を含む語同士を literal で継ぐ。"""
    out: list[Seg] = []
    for index, word in enumerate(words):
        if index:
            out.append(Seg(separator))
        out.extend(word)
    return tuple(out)

# ----------------------------------------------------------------- shell rendering

_NEEDS_QUOTES = re.compile(r"[^A-Za-z0-9_@%+=:,./-]")


def render_word(word: Word) -> str:
    """語 1 つをシェルの字面へ。変数を含む語は必ず二重引用符で括る。"""
    if not any(seg.is_var for seg in word):
        text = "".join(seg.text for seg in word)
        if text and not _NEEDS_QUOTES.search(text):
            return text
        return "'" + text.replace("'", "'\\''") + "'"
    out = ['"']
    for seg in word:
        if seg.is_var:
            out.append("${" + seg.text + "}")
        else:
            out.append(re.sub(r'([\\"$`])', r"\\\1", seg.text))
    out.append('"')
    return "".join(out)


def render_command(command: list[Word], *, indent: str = "  ") -> str:
    """1 コマンドを複数行に折る。``docker run`` を 1 行目に置き、以降はフラグと値で 1 行。"""
    rendered = [render_word(word) for word in command]
    head = " ".join(rendered[:2])
    lines: list[str] = []
    position = 2
    while position < len(rendered):
        item = rendered[position]
        following = rendered[position + 1] if position + 1 < len(rendered) else None
        if item.startswith("-") and following is not None and not following.startswith("-"):
            lines.append(f"{item} {following}")
            position += 2
            continue
        lines.append(item)
        position += 1
    if not lines:
        return head
    body = f" \\\n{indent}".join(lines)
    return f"{head} \\\n{indent}{body}"


def render_run_sh(plan: PublishPlan) -> str:
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by `kikai publish {plan.name}` — 手で書き換えないこと。",
        "# 値は env.example を .env に写して埋める。",
        "set -euo pipefail",
        "",
        'PUBLISH_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        "",
        'if [ -f "$PUBLISH_ROOT/.env" ]; then',
        "  set -a",
        '  # shellcheck disable=SC1091',
        '  . "$PUBLISH_ROOT/.env"',
        "  set +a",
        "fi",
        "",
    ]
    if plan.variables:
        lines.append("# 未設定のまま走ると空パスを mount してしまうので、先に落とす。")
        for spec in plan.variables:
            lines.append(
                f': "${{{spec.name}:?{spec.name} is not set — see env.example}}"'
            )
        lines.append("")
    total = len(plan.ops)
    for op in plan.ops:
        header = f"# [{op.index}/{total}] {op.operation} (adapter={op.adapter})"
        if op.command is None:
            lines.append(f"{header} — SKIPPED, not published")
            for reason_line in op.skipped_reason.splitlines() if op.skipped_reason else []:
                lines.append(f"#   reason: {reason_line}")
            lines.append("#   この位置の処理はパッケージに含まれない。README を読むこと。")
            lines.append("")
            continue
        lines.append(f"{header} bundle={op.bundle_id} entrypoint={op.entrypoint}")
        lines.append(render_command(op.command))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_env_example(plan: PublishPlan) -> str:
    lines = [
        f"# {plan.name} — ホスト固有の値。埋めてから `.env` に写す。",
        "# 秘密の値は kikai から持ち出していない (鍵の名前だけがここにある)。",
        "",
    ]
    if not plan.variables:
        lines.append("# このパッケージにホスト固有値は無い。")
        return "\n".join(lines) + "\n"
    for spec in plan.variables:
        lines.append(f"# {spec.origin}")
        if spec.example is not None:
            lines.append(f"# publish 元での値: {spec.example}")
        lines.append(f"{spec.name}=")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_readme(plan: PublishPlan) -> str:
    lines = [
        f"# {plan.name}",
        "",
        "`kikai publish` が書き出した自己完結パッケージ。kikai は要らない。",
        "docker と、下に並ぶ前提が揃っていれば走る。",
        "",
        "## 使い方",
        "",
        "```",
        "cp env.example .env",
        "$EDITOR .env      # ホスト固有の値を埋める",
        "bash run.sh",
        "```",
        "",
        "## 中身",
        "",
        "| パス | 何 |",
        "| --- | --- |",
        "| `run.sh` | op 列を依存順に並べた `docker run` コマンド列 |",
        "| `env.example` | ホスト固有値の一覧 (値は空) |",
        f"| `{PACKAGE_BUNDLE_DIR}/` | 実行する script bundle の実体 (`bundle.json` に sha256) |",
        "",
        "## 前提",
        "",
        "### イメージ",
        "",
    ]
    if plan.images:
        lines.append("次のイメージが docker から見えること (名前は `.env` で指定する):")
        lines.append("")
        for name in plan.images:
            lines.append(f"- `{name}`")
    else:
        lines.append("(このパッケージが使うイメージは無い)")
    lines += ["", "### GPU", ""]
    gpu_ops = [
        op
        for op in plan.translated
        if any(seg.text == "--gpus" for word in op.command or [] for seg in word)
    ]
    if gpu_ops:
        lines.append("`--gpus` を渡す op があるので、NVIDIA Container Toolkit が要る:")
        lines.append("")
        for op in gpu_ops:
            lines.append(f"- `{op.operation}`")
    else:
        lines.append("GPU を要求する op は無い。")
    lines += ["", "### データ配置", ""]
    if plan.mounts:
        lines.append("| 変数 | コンテナ内のパス | mode | publish 元での値 |")
        lines.append("| --- | --- | --- | --- |")
        for row in plan.mounts:
            example = f"`{row.source_example}`" if row.source_example else "(kikai 側も変数)"
            lines.append(f"| `{row.variable}` | `{row.target}` | `{row.mode}` | {example} |")
        lines.append("")
        lines.append(
            "`mode` は publish 元のまま。`ro` の口に書き込む処理は無いので、緩めないこと。"
        )
    else:
        lines.append("ホストから持ち込むデータは無い。")
    lines += ["", "## 含まれない op", ""]
    if plan.skipped:
        lines.append("次の op は docker CLI へ翻訳できないので **パッケージから除外した**。")
        lines.append("同じ効果が要るなら受け手側で用意すること。")
        lines.append("")
        lines.append("| 位置 | operation | adapter | 理由 |")
        lines.append("| --- | --- | --- | --- |")
        for op in plan.skipped:
            lines.append(
                f"| {op.index}/{len(plan.ops)} | `{op.operation}` | `{op.adapter}` | "
                f"{op.skipped_reason} |"
            )
    else:
        lines.append("無し。渡された op はすべて翻訳した。")
    lines += ["", "## kikai 側との差", ""]
    lines.append("実行に効かない、あるいは kikai 固有の取り決めは落としてある:")
    lines.append("")
    lines.append(
        f"- project_root 全体の ro マウントの代わりに、`{PACKAGE_BUNDLE_DIR}/` だけを "
        f"`{CONTAINER_BUNDLE_DIR}` へ被せる (レジストリの他の記録は配らない)"
    )
    lines.append(
        "- `env:NAME` の中に更に `${...}` が入っていても、publish は 1 段しか展開しない"
    )
    for note in plan.dropped_notes:
        lines.append(f"- {note}")
    lines += ["", "## 出所", ""]
    lines.append("| bundle | ファイル数 |")
    lines.append("| --- | --- |")
    for bundle_id, root in plan.bundle_roots.items():
        count = sum(1 for path in (root / "root").rglob("*") if path.is_file())
        lines.append(f"| `{bundle_id}` | {count} |")
    lines.append("")
    lines.append(
        "publish は snapshot。書き出したあとに kikai 側のレジストリが変わっても、"
        "このパッケージは追随しない。"
    )
    return "\n".join(lines).rstrip("\n") + "\n"

# ------------------------------------------------------------------------ output


# ------------------------------------------------------------------------ output


def write_package(plan: PublishPlan, out_dir: Path) -> dict[str, Any]:
    """パッケージをディスクへ。既存で空でなければ拒否する (上書きしない)。"""
    if out_dir.exists() and any(out_dir.iterdir()):
        raise OperationError(
            "publish.output_exists",
            f"publish output directory is not empty: {out_dir}",
            {"out_dir": str(out_dir)},
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    bundles_dir = out_dir / PACKAGE_BUNDLE_DIR
    bundles_dir.mkdir(exist_ok=True)
    for bundle_id, bundle_root in plan.bundle_roots.items():
        shutil.copytree(bundle_root, bundles_dir / bundle_id)
    run_sh = out_dir / "run.sh"
    run_sh.write_text(render_run_sh(plan), encoding="utf-8")
    run_sh.chmod(0o755)
    (out_dir / "env.example").write_text(render_env_example(plan), encoding="utf-8")
    (out_dir / "README.md").write_text(render_readme(plan), encoding="utf-8")
    return {
        "publish_name": plan.name,
        "out_dir": str(out_dir),
        "operations_total": len(plan.ops),
        "operations_published": len(plan.translated),
        "operations_skipped": [
            {
                "index": op.index,
                "operation": op.operation,
                "adapter": op.adapter,
                "reason": op.skipped_reason,
            }
            for op in plan.skipped
        ],
        "bundles": sorted(plan.bundle_roots),
        "variables": [spec.name for spec in plan.variables],
    }

